version: '3'

services:
  placement:
    command: ["./placement", "--port", "50006"]
    ports:
    - 50006:50006

  redis:
    ports:
    - 6379:6379

  rabbitmq:
    ports:
    - 5672:5672
    - 15672:15672
    
  orderapi:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 8000:5000

  garbagecollector:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 8001:5000