version: '3'

services:
  placement:
    image: daprio/dapr
    container_name: placement
    networks:
    - dapr

  redis:
    image: redis:6
    container_name: redis
    networks:
    - dapr

  orderapi:
    image: orderapi:dev
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
      tags:
      - orderapi:dev
    environment:
    - ASPNETCORE_URLS=http://+:5000
    depends_on:
    - redis
    networks:
    - dapr

  orderapi-dapr:
    image: daprio/daprd
    command: ["./daprd",
      "--app-id", "orderapi",
      "--app-port", "5000",
      "--placement-host-address", "placement:50006",
      "--components-path", "/components"]
    volumes:
    - ./dapr/components/:/components
    depends_on:
    - orderapi
    - placement
    network_mode: "service:orderapi"
    networks:
    - dapr

  orderactor:
    image: orderactor:dev
    build:
      context: .
      dockerfile: OrderActor/Dockerfile
      tags:
      - orderactor:dev
    environment:
    - ASPNETCORE_URLS=http://+:5000
    depends_on:
    - redis
    networks:
    - dapr

  orderactor-dapr:
    image: daprio/daprd
    command: ["./daprd",
      "--app-id", "orderapi",
      "--app-port", "5000",
      "--placement-host-address", "placement:50006",
      "--components-path", "/components"]
    volumes:
    - ./dapr/components/:/components
    depends_on:
    - orderactor
    - placement
    network_mode: "service:orderactor"
    networks:
    - dapr

networks:
  dapr: null