version: '3'

services:
  placement:
    image: daprio/dapr
    container_name: placement
    networks:
    - dapr

  redis:
    image: redis:6
    container_name: redis
    networks:
    - dapr

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
    - dapr

  orderapi:
    image: orderapi:dev
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
      tags:
      - orderapi:dev
    environment:
    - ASPNETCORE_URLS=http://+:5000
    depends_on:
    - redis
    - rabbitmq
    networks:
    - dapr

  orderapi-dapr:
    image: daprio/daprd
    command: ["./daprd",
      "--app-id", "orderapi",
      "--app-port", "5000",
      "--placement-host-address", "placement:50006",
      "--components-path", "/components"]
    volumes:
    - ./dapr/components/:/components
    depends_on:
    - orderapi
    - placement
    network_mode: "service:orderapi"
    networks:
    - dapr

  # garbagecollector:
  #   image: garbagecollector:dev
  #   build:
  #     context: .
  #     dockerfile: GarbageCollector/Dockerfile
  #     tags:
  #     - garbagecollector:dev
  #   environment:
  #   - ASPNETCORE_URLS=http://+:5000
  #   depends_on:
  #   - rabbitmq
  #   networks:
  #   - dapr

  # garbagecollector-dapr:
  #   image: daprio/daprd
  #   command: ["./daprd",
  #     "--app-id", "garbagecollector",
  #     "--app-port", "5000",
  #     "--placement-host-address", "placement:50006",
  #     "--components-path", "/components"]
  #   volumes:
  #   - ./dapr/components/:/components
  #   depends_on:
  #   - garbagecollector
  #   - placement
  #   network_mode: "service:garbagecollector"
  #   networks:
  #   - dapr

networks:
  dapr: null
