version: '3'

services:
  placement:
    command: ["./placement", "--port", "50006"]
    ports:
    - 50006:50006

  redis:
    ports:
    - 6379:6379
    
  orderapi:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:5000
    ports:
    - 8000:5000

  orderactor:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:5000
    ports:
    - 9000:5000

