apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my_data
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"